name: reddit
version: 1.0.0
description: OTUS reddit application UI
maintainers:
  - name: krang404
    email: krang404@example.ru
appVersion: 1.0

dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../ui"

  - name: post
    version: "1.0.0"
    repository: "file://../post"

  - name: comment
    version: "1.0.0"
    repository: "file://../comment"

  - name: mongodb
    version: "12.1.27"
    repository: https://charts.bitnami.com/bitnami

  - name: ingress-nginx
    version: "4.1.4"
    repository: https://kubernetes.github.io/ingress-nginx
...
