---
- import_playbook: ./playbooks/install_docker.yml
- import_playbook: ./playbooks/install_k8s.yml
- import_playbook: ./playbooks/init_master.yml
- import_playbook: ./playbooks/join_worker.yml
- import_playbook: ./playbooks/apply_manifest.yml
