---
- name: Apply Manifest
  hosts: master
  tasks:

  - name: Copy manifest
    copy:
      src: ../../reddit/{{ item }}
      dest: $HOME/{{ item }}
    with_items:
      - comment-deployment.yml
      - mongo-deployment.yaml
      - post-deployment.yml
      - ui-deployment.yml

  - name: Apply Deployment
    command: kupectl apply -f {{ item }}
    args:
      chdir: $HOME
    with_items:
      - comment-deployment.yml
      - mongo-deployment.yml
      - post-deployment.yml
      - ui-deployment.yml
