FROM python:3.6.0-slim

WORKDIR /app
ADD . /app

RUN apt-get update -qq && apt-get install -y g++ gcc make && \
    pip install -r /app/requirements-for-slim.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
