source 'https://rubygems.org'

gem 'sinatra', '~> 2.0.1'
gem 'haml'
gem 'bson_ext'
gem 'bcrypt', '>=3.1.11'
gem 'puma', '>= 3.10.0'
gem 'mongo'
gem 'json', '>= 2.1.0'
gem 'rack-test'

group :development do
    gem 'capistrano',         require: false
    gem 'capistrano-rvm',     require: false
    gem 'capistrano-bundler', require: false
    gem 'capistrano3-puma',   require: false
end
