version: '3.3'

services:
  ui:
    command: puma --debug -w 2
    volumes:
      - volume_ui:/app

  post:
    volumes:
      - volume_post:/app

  comment:
    command: puma --debug -w 2
    volumes:
      - volume_comment:/app

volumes:
  volume_ui:
  volume_comment:
  volume_post:
